### ISSUE TITLE
Calling setUserId from a server function

### ISSUE THREAD

**Issue by uriva** [netanelgilad/meteor-angular-server#2]
Hi,
I'm implementing my own authentication mechanism.
At a certain point I need to call `setUserId` in a server side provider.
can this method be exposed somehow?

**Comment by netanelgilad** [comment]
Actually this should be possible I think.
If you are inside a call to a function exposed on the server you should be able to use this.setUserId since In angular-meteor I call the service function with a `this` that is the same `this` as the one of a `Meteor.method`. Tell me if that works for you, and if you have a code sample for your case, maybe i'll get a better picture..

**Comment by uriva** [comment]
oh
cool
worked.
